### ISSUE TITLE
5.3 リリース

### ISSUE THREAD

**Issue by zmatsuo** [TeraTermProject/teraterm#274]
- リリース予定日 8月末
- 前リリース(5.2) #124

[Tera Term Q & A](https://teratermproject.github.io/manual/5/ja/about/qanda.html)
> 定期リリースは 6 ヶ月に一回、2月/8月の末に出ます。

### tasklist

- [x] リリースに入れたいもの確認
  - [x] COMポート並び順 #270
  - [x] getttpos #234
  - [x] MessageBox の位置 #234
  - [x] getttpos DPIAware=off時の動き
  - setdlgpos の拡張 #279
    - これは5.4へ
  - [x] SSH UTF-8 username, password #276
  - [x] SSH multiple required authentication #99
  - [x] 言語ファイルの修正#286
  - [x] ポータブル版の場合、言語が2回表示される #288
  - [x] TTXKanjiMenu #301
  - [x] ドキュメント: Languageの削除
  - [x] TTXKanjiMenu: bump up, document
- [x] ライブラリバージョン確認
- [x] 変更履歴整理
- [x] RC作成
- [リリース](https://teratermproject.github.io/manual/5/ja/reference/develop-release.html)
  - [x] バイナリ作成
  - [x] アナウンス
  - [x] webページ更新
  - [x] Edge の「一般的にダウンロードされていません」がなくなることを確認
  - [x] SmartScreen の「WindowsによってPCが保護されました」がなくなることを確認
  - ~~[ ] Chocolatey~~

### その他

5.2 の Chocolatey の登録 #138 をすすめられないかなと
サイトを見たりしていたのですが
どうやればいいのかわからずです。

登録はリリースと同時でなくてもよいかなと思いますがいかがでしょう?
リクエストも特にないですしそれほど需要がないのかな。

To 開発チーム
今のところ main ブランチには大きな不具合はない認識でいます。
リリースまでに入れたいもの/入れたほうが良いものなどありますか?

**Comment by hkanou** [comment]
>tasklist
 リリースに入れたいもの確認

#234 で追加させていただいた getttpos コマンドに下記の不具合が見つかりました。
申し訳ありませんが 5.3 リリースまでに修正させて頂ければと思います。
「TERATERM.INI で DpiAware=off を指定し、ディスプレイの拡大/縮小率を100%(96dpi)以外にしている場合に、取得した VT window のX,Y座標とサイズがずれている」
後ほど、修正版のPRをお送りさせて頂きます。

**Comment by hkanou** [comment]
> #234 で追加させていただいた getttpos コマンドに下記の不具合が見つかりました。

修正パッチをお送りさせて頂きました。(併せてマニュアルの例の誤記を修正しています)
https://github.com/hkanou/teratermproject_teraterm/commit/8ffcb3e55a329bf418bcf2305e7e0d986616ad1e

**Comment by nmaya** [comment]
### リリースに入れたいもの

- #234 getttpos
  - #275 の件以外は完了しているでしょうか？
- #234 MessageBox の位置
  - 作業中でしょうか？
- #275 getttpos DPIAware=off時の動き
  - 確認中でしょうか？
- #279 setdlgpos の拡張
  - これは5.4へ

#276, #99 はどうしましょうか？

**Comment by nmaya** [comment]
### ライブラリバージョン確認

Inno Setup の最新は 6.3.3 ですが、[開発環境・ライブラリ](https://teratermproject.github.io/manual/5/ja/reference/develop-environment.html) には 6.2.2 と記載されています。
AppVeyor でビルドするときに使われるInno Setupは、AppVeyor が用意しているものですか？であれば、バージョンはこちらで選べないことになりますが、それで合っていますか？

**Comment by zmatsuo** [comment]
#276 テストできたのでクローズしました。

#99 明日テストしますね。
テストしてよさそうだったらマージしましょう。

**Comment by zmatsuo** [comment]
bulidtools/ に Inno Setup をダウンロードしておけば、自動的に使われるはずです。
なければシステムにインストールされているものを使います。
ダウンロードは buildtools/install_innosetup.bat をコールすればokです。

**Comment by hkanou** [comment]
- #234 getttpos
  > https://github.com/TeraTermProject/teraterm/issues/275 の件以外は完了しているでしょうか？

  完了しました。(#275含む)

- https://github.com/TeraTermProject/teraterm/issues/234 MessageBox の位置
  > 作業中でしょうか？

  作業中です。
  残りは、MessageBoxPosParentRelativeオプション廃止対応(ソース、ドキュメント修正)になります。

- https://github.com/TeraTermProject/teraterm/issues/275 getttpos DPIAware=off時の動き
  > 確認中でしょうか？

  完了しました。getttposのPRを出させて頂きました。  

- https://github.com/TeraTermProject/teraterm/issues/279 setdlgpos の拡張
  > これは5.4へ

  5.4でのリリースになりそうです。

**Comment by nmaya** [comment]
> bulidtools/ に Inno Setup をダウンロードしておけば

ありがとうございます。
#283 に移動します。

**Comment by nmaya** [comment]
### ライブラリバージョン確認

Inno Setup 6.3.3 に更新しました。

**Comment by nmaya** [comment]
main にいろいろマージして、AppVeyor のビルドをかけました。プログラム動作のチェックはこちらから可能です。
https://ci.appveyor.com/project/teraterm/github-main/builds/50468459

可能なら今日中にドキュメントのチェックを行います。

リリース文面も考えます。

**Comment by zmatsuo** [comment]
ログインできない場合があり悩んでいました。
sshd(ホスト側)設定の組み合わせでログインできなくなるようです。
```
# sshd -V
OpenSSH_9.8p1 Debian-2, OpenSSL 3.2.2 4 Jun 2024
```

ちょっとはまっていました。

### 詳細

/etc/pam.d/sshd
```
auth required pam_unix.so nullok
auth required pam_google_authenticator.so nullok
```

となっていて、
~/.google_authenticator
が存在している状態の時、

/etc/ssh/sshd_config
```
PasswordAuthentication yes
ChallengeResponseAuthentication yes
AuthenticationMethods password
```

だとログインできません。

~/.google_authenticator
が存在していない時はログインできます。


~/.google_authenticator
が存在していて

/etc/ssh/sshd_config
```
PasswordAuthentication yes
ChallengeResponseAuthentication yes
AuthenticationMethods keyboard-interactive
```

の時はログインできます(keyboard-interactiveとなります)

**Comment by hkanou** [comment]
変更履歴を整理頂きありがとうございます。
修正案は以下のとおりです。

teraterm/doc/en/html/about/history.html (英語版)
```
80行目 行頭に"MACRO: "を追加
<li>MACRO: added the <a href="../macro/command/getttpos.html">getttpos</a> command to retrieve the display status, position, and size in the VT window of Tera Term.</li>

109行目 "ttermpro.exe の /V オプションを使用すると終了時クラッシュする問題を修正した。"の追加
<li>Fixed the issue where specifying the <a href="../commandline/teraterm.html#v">/V option</a> with ttermpro.exe would cause a crash upon exit.</li>
```

**Comment by nmaya** [comment]
確認ありがとうございます。

> 変更履歴を整理頂きありがとうございます。 修正案は以下のとおりです。
> 
> 109行目 "ttermpro.exe の /V オプションを使用すると終了時クラッシュする問題を修正した。"の追加
> <li>Fixed the issue where specifying the <a href="../commandline/teraterm.html#v">/V option</a> with ttermpro.exe would cause a crash upon exit.</li>

`<li>Fixed crash on exit when using <a href="../commandline/teraterm.html#v">/V option</a> of ttermpro.exe.</li>` があったのですが、[33a6057](https://github.com/TeraTermProject/teraterm/commit/33a60573ce46704af24cab4d656425c932d075b8) の位置の修正で消してしまったようです。ご提案の文面で追加しました。

**Comment by sempreff** [comment]
変更履歴のまとめブランチを拝見しました。
一箇所だけ気になったのでご報告いたします。

「Default port 設定を Additional settings の General タブへ移動した。」について、後で
「Default port 設定を TCP/IP タブへ移動した。」が出てくることで
最終的に「General」でなく「TCP/IP setup」に移動しています。
両者は、まとめるのが良さそうに思われます。

**Comment by zmatsuo** [comment]
指摘ありがとうございます。
Default port 設定の変更履歴を1つにまとめまた修正案をpushしました。

**Comment by zmatsuo** [comment]
> Default port 設定の変更履歴を1つにまとめまた修正案をpushしました。

ブランチ元がいまいちだったので修正しました。

**Comment by nmaya** [comment]
「入れたいもの」をすべてマージし、ビルドをかけました。
https://ci.appveyor.com/project/teraterm/github-main/builds/50487026

**Comment by nmaya** [comment]
RCは今晩出します。

**Comment by nmaya** [comment]
RC をアナウンスしました。
https://x.com/Tera_Term/status/1828773687375581236

**Comment by zmatsuo** [comment]
RC出た後なのですが・・。
ドキュメント内のリンクが良くないところを見つけたので修正しました。
3b026d601a6dac02aaca350d153de206f3cb0225

**Comment by zmatsuo** [comment]
ダイアログをvtwinの中央に移動するためのコードがtabの初期化の中に残っていました。
今まで動作を見ている感じ問題なさそうですが、削除しました。
3e3cab2504cd82b7ce6d5c31d76013f079a21aa1

**Comment by nmaya** [comment]
すみません、気づかなかったのですが #84 の 23f3f19ffdf5cc8e99ccc86b83ed5585ae260a38 で「Default port」が TCP/IP タブに移動しています。
New connection のデフォルトを「TCP/IP」にするか「Serial」にするかを TCP/IP タブの中で選ぶのは違和感があり、General にあるべきと思いますがいかがですか？cf. https://github.com/TeraTermProject/teraterm/issues/84#issuecomment-2317551917

**Comment by sempreff** [comment]
私も違和感あります。

**Comment by zmatsuo** [comment]
> Additional Settings の TCP/IP だけタブ名に「setup」と付いているのも気になります

setup と付いているのはダイアログタイトルのなごりかな
"TCP/IP" だけに変更します。

**Comment by zmatsuo** [comment]
70d56fd126e564fef01113651ed0470469936fc8 👍

**Comment by nmaya** [comment]
> "TCP/IP" だけに変更します。

修正ありがとうございます。

> ひとまず違和感少ない General タブに戻しましょう。

こちらもありがとうございます。
リリースを何日か後ろにずらしましょう。

**Comment by zmatsuo** [comment]
#274 (デフォルトポートをGeneralタブへ移動する) 直します。
それ以外は良さそうなので main へマージしました。

**Comment by sempreff** [comment]
細かい手直しを #295 #296 #297 で上げました。
いずれも軽微なものなので issue を立てておりません。
間に合えば 5.3 に入れ込んでいただけると幸いです。

**Comment by nmaya** [comment]
> 細かい手直しを #295 #296 #297 で上げました。

ありがとうございます。マージしました。

**Comment by sempreff** [comment]
五月雨ですみません。 #300 を上げました。

**Comment by sempreff** [comment]
[usage/unicode.html](https://teratermproject.github.io/manual/5/ja/usage/unicode.html) に書かれている Language の選択方法は既になくなってしまっているので、大幅に書き直す必要があると思います。5.3 での変更なので 5.3 に間に合うと良いと思いますが、いかがでしょうか。

**Comment by hkanou** [comment]
直前で申し訳ございませんが #301 のPRを出させて頂きました。
5.3 に入れて頂けると良いのですが...、ご確認頂ければと存じます。

**Comment by zmatsuo** [comment]
対応する英語版も修正しました。

**Comment by nmaya** [comment]
> 修正しました。

ありがとうございます。

> Unicodeに関連した説明

「簡単な設定の方法」以下の記述でしょうか。
まとまっているのは良いことだと思いますが、Unicode 固有でないのにそこに移動してしまうと技術的に正しくなくなるのと、設定しようと思って読むときに行ったり来たりするのが読みやすいか、加減が難しいですね。

**Comment by sempreff** [comment]
修正ありがとうございます。

unicode.html については、２つ気付いた点があります。
* Chinese を China と表記している理由はどのあたりでしょうか。特に意図がなければ、Chinese が良いと思います。
* コマンドラインへの言及は必要でしょうか。その場合はリンクがあると尚良さそうです。個人的にはコマンドラインへの言及は無くても良さそうに思います。

関連して commandline/teraterm.html についても手当てしてあるとさらに良いと思います。
* コマンドラインで /KR=UTF8 /KT=UTF8 /LA=R のようにすると、/LA が勝つようです。将来的に /LA はどう扱われるでしょうか。
  * 引き続き利用可能とすると、類似のオプションで優先順位があることになりますから、それが記載されていると良いと思います。
  * 将来的に /LA を落としていく方向性だとすると、5.3 時点で deprecated である旨を記載しておくと良いと思います。

（なお、いずれも リリースを遅らせてまで 5.3 で対応すべき事項ではないと思います）

**Comment by zmatsuo** [comment]
コマンドラインから ts.Language を変更できますね。
指定する文字コードとLanguage(言語)の組み合わせによっては問題が出る気がします。

/KT,/KR の値から、Language(言語)は自動で(一意に)決定できます。
/LA はなくすよう修正します。

**Comment by zmatsuo** [comment]
> Chinese を China と表記している理由はどのあたりでしょうか。特に意図がなければ、Chinese が良いと思います

Codingタブの設定が "China/Big5" になっているからですね。
どうして Chinese にしなかったのか…🤔

Chinese に変更します。

**Comment by zmatsuo** [comment]
> これは #306 に移動します。
> Coding タブ・コマンドラインの動きは新しいものではないので 5.4 に回しましょう。

了解です。そうしましょう。

一段落として main にマージします。

**Comment by zmatsuo** [comment]
マージしました。

手もとで直したところをチェックしました。問題なさそうです。
ぎりぎりまで修正してご迷惑をおかけしました。

Appveyor の github-main を RC2、マージしたところ(f9e55b49453c6f4486b7a0b2cb5cdfbf4592f123) で
ビルドスタートしました。

バイナリができるはずです。
https://ci.appveyor.com/project/teraterm/github-main/builds/50543619/artifacts

**Comment by nmaya** [comment]
#306 を見ていて #308 に気づきましたが、これのマイルストーンも 5.4 にしました。
#309 はドキュメントだけで済むのでねじ込みました。

**Comment by sempreff** [comment]
TTXKanjiMenu の 5.3 での変更としては commit 9babd50 があって、その後 #265, #301 ですね。
https://github.com/TeraTermProject/teraterm/commits/9babd5001028e4a5166da2f4e9ed5b6d2cf4f6b3/TTXKanjiMenu/ttxkanjimenu.c

**Comment by zmatsuo** [comment]
履歴追加、バージョン++します。

**Comment by zmatsuo** [comment]
@sempreff さんの指摘通りです。
日付順に並べました。

- 2024.9.3
  - 1937754af0df5ea6f7daaa7067156a14ed78f52d
  - #301 TTXKanjiMenuのACCESS_VIOLATION
- 2024.8.1
  - 0ca791ea3a247313981378a732eaa854f99ba474
  - #265 漢字コードが正しく選択できない場合があったので修正
- 2024.6.17
  - 9babd5001028e4a5166da2f4e9ed5b6d2cf4f6b3
  - メニューの作成を簡単にした
- 2024.2.29
  - Tera Term Ver 5.2

リファクタリングの結果バグを出してしまいました。
失礼しました。
5.2からは特に機能追加は行っていません。

**Comment by nmaya** [comment]
> f733171891d1c5a780abc4128c8ce09b72cea0f1

対応ありがとうございます。

> Tera Term 5.2からは特に機能追加は行っていません。

どちらも 9babd5001028e4a5166da2f4e9ed5b6d2cf4f6b3 によって起きた不具合の修正だったんですね、わかりました。
5.2 リリースをまたいでいないので、書いて頂いたように「 9babd5001028e4a5166da2f4e9ed5b6d2cf4f6b3 の変更履歴を入れる」でよいと思います。

**Comment by zmatsuo** [comment]
> この処理は[ここ](https://github.com/TeraTermProject/teraterm/blob/176aed2671bda031f2d0c0b09af463feba8e428c/teraterm/ttpset/ttset.c#L3980)かな？と思います。

ですね、これで

> * コマンドラインで /KR=UTF8 /KT=UTF8 /LA=R のようにすると、/LA が勝つようです。

/LA が優先されて設定されて、
問題ある組み合わせにはならないですね。
いまの main (b85f2e3a4a7fb63954fdefd1a8229d29ce5df302) でokそうです。

**Comment by sempreff** [comment]
https://github.com/TeraTermProject/teraterm/issues/274#issuecomment-2321384976
の件、Default Port は最終的に General タブに落ち着いたので、history.html も追従が必要ですね。

**Comment by nmaya** [comment]
[5.3をリリース](https://github.com/TeraTermProject/teraterm/releases/tag/v5.3)しました。
ご協力ありがとうございました。

**Comment by nmaya** [comment]
Chocolatey は #138 の問題があるので、ひとまずウイルス対策ソフトの反応を見てから考えようと思います。

**Comment by sempreff** [comment]
https://teratermproject.github.io/ の下部の言語ファイルの一覧も更新されると良いと思います。

**Comment by nmaya** [comment]
Edge でダウンロードしたとき「一般的にダウンロードされていません」が出なくなりました。

**Comment by nmaya** [comment]
窓の杜ライブラリに「ポータブル版」だけ載りました。
https://forest.watch.impress.co.jp/docs/update/library/1622810.html

「一般的にダウンロードされていません」が出なくなったので、そのうちインストーラ版も載ると思います。

**Comment by nmaya** [comment]
SmartScreen の「WindowsによってPCが保護されました」が出なくなっていました。

窓の杜は 9/13 にインストーラ版が載ったようです。
https://forest.watch.impress.co.jp/docs/update/library/1623497.html
